# Generated by Django 5.1.2 on 2024-10-31 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("Tenge", "Tenge"),
                            ("Ruble", "Ruble"),
                            ("Dollar", "Dollar"),
                            ("Euro", "Euro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="format: YY-MM-DD hh:mm:ss, auto-generated",
                        null=True,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="format: YY-MM-DD hh:mm:ss, auto-generated",
                        null=True,
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "owner_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Budget",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="format: YY-MM-DD hh:mm:ss, auto-generated",
                        null=True,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="format: YY-MM-DD hh:mm:ss, auto-generated",
                        null=True,
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "budget_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Category",
                        to="money_manager.budget",
                        verbose_name="Budget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("Income", "Income"), ("Spending", "Spending")],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="format: YY-MM-DD hh:mm:ss, auto-generated",
                        null=True,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="format: YY-MM-DD hh:mm:ss, auto-generated",
                        null=True,
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "budget_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Transaction",
                        to="money_manager.budget",
                        verbose_name="Budget",
                    ),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Transaction",
                        to="money_manager.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
